name: Snake Game

on:
  schedule:
    - cron: "0 */5 * * *" # Atualiza a cada 5 horas
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Faz o checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v2

      # Gera os arquivos do Snake Game
      - name: Generate Snake Game
        uses: Platane/snk@v2
        with:
          github_user_name: edernatanzz # Substitua pelo seu nome de usuário

      # Commit e push das alterações
      - name: Commit changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add -A
          git commit -m "Generate Snake Game" || echo "No changes to commit"
          git push origin HEAD:output
